config/routes.rb
Rails.application.routes.draw do
  resources :takes
  resources :people

end

app/models/person.rb
class Person < ActiveRecord::Base
	has_many :takes, dependent: :destroy
end

app/models/take.rb
class Take < ActiveRecord::Base
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @takes = @person.takes
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:vk, :name)
    end
end

app/controllers/takes_controller.rb
class TakesController < ApplicationController
  before_action :set_take, only: [:show, :edit, :update, :destroy]

  # GET /takes
  # GET /takes.json
  def index
    @takes = Take.all
  end

  # GET /takes/1
  # GET /takes/1.json
  def show
  end

  # GET /takes/new
  def new
    @take = Take.new
  end

  # GET /takes/1/edit
  def edit
  end

  # POST /takes
  # POST /takes.json
  def create
    @take = Take.new(take_params)

    respond_to do |format|
      if @take.save
        format.html { redirect_to @take, notice: 'Take was successfully created.' }
        format.json { render :show, status: :created, location: @take }
      else
        format.html { render :new }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /takes/1
  # PATCH/PUT /takes/1.json
  def update
    respond_to do |format|
      if @take.update(take_params)
        format.html { redirect_to @take, notice: 'Take was successfully updated.' }
        format.json { render :show, status: :ok, location: @take }
      else
        format.html { render :edit }
        format.json { render json: @take.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /takes/1
  # DELETE /takes/1.json
  def destroy
    @take.destroy
    respond_to do |format|
      format.html { redirect_to takes_url, notice: 'Take was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_take
      @take = Take.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def take_params
      params.require(:take).permit(:online, :person_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/takes_helper.rb
module TakesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineVk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.slim
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      h2 = "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      ul
        - @person.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :vk
    = f.number_field :vk
  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/people/edit.html.slim
h1 Editing person

== render 'form'

= link_to 'Show', @person
'|
= link_to 'Back', people_path

app/views/people/index.html.slim
h1 Listing people

table
  thead
    tr
      th Vk
      th Name
      th
      th
      th

  tbody
    - @people.each do |person|
      tr
        td = person.vk
        td = person.name
        td = link_to 'Show', person
        td = link_to 'Edit', edit_person_path(person)
        td = link_to 'Destroy', person, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Person', new_person_path

app/views/people/new.html.slim
h1 New person

== render 'form'

= link_to 'Back', people_path

app/views/people/show.html.slim
p#notice = notice

p
  strong Vk:
  = @person.vk
p
  strong Name:
  = @person.name

-@takes.each do |take|
	=take.created_at+3.hours
	|&nbsp
	=take.online
	br

= link_to 'Edit', edit_person_path(@person)
'|
= link_to 'Back', people_path

app/views/takes/_form.html.slim
= form_for @take do |f|
  - if @take.errors.any?
    #error_explanation
      h2 = "#{pluralize(@take.errors.count, "error")} prohibited this take from being saved:"
      ul
        - @take.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :online
    = f.check_box :online
  .field
    = f.label :person
    = f.text_field :person
  .actions = f.submit

app/views/takes/edit.html.slim
h1 Editing take

== render 'form'

= link_to 'Show', @take
'|
= link_to 'Back', takes_path

app/views/takes/index.html.slim
h1 Listing takes

table
  thead
    tr
      th Online
      th Person
      th
      th
      th

  tbody
    - @takes.each do |take|
      tr
        td = take.online
        td = lnkk_to take.person.name, "https://vk.com/id#{take.person.vk}"
        td = link_to 'Show', take
        td = link_to 'Edit', edit_take_path(take)
        td = link_to 'Destroy', take, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Take', new_take_path

app/views/takes/new.html.slim
h1 New take

== render 'form'

= link_to 'Back', takes_path

app/views/takes/show.html.slim
p#notice = notice

p
  strong Online:
  = @take.online
p
  strong Person:
  = @take.person

= link_to 'Edit', edit_take_path(@take)
'|
= link_to 'Back', takes_path